version: 2

sources:
  - name: raw
   # database: notional-mantra-457509-n6.gz_raw_data
    schema: gz_raw_data
    tables:
      - name: raw_gz_sales
      - name: raw_gz_product
      - name: raw_gz_ship
